Repository openshift/ironic-agent-image, pull requests merged in 2022-06, with the labels that each got.

#51 Bug 2089309: multipath fix for passive paths
  packages-list.ocp
Labels: bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, approved

#52 Bug 2089312: multipath fix for passive paths
  packages-list.ocp
Labels: bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed

#53 Bug 2098392: Include Fix discovering WWN/serial for devicemapper devices
  packages-list.ocp
Labels: bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, approved

#54 Bug 2100749: Add missing multipath modules
  packages-list.ocp
  packages-list.okd
Labels: bugzilla/valid-bug, bugzilla/severity-high, lgtm, approved
