Repository openshift/ironic-agent-image, pull requests merged in 2022-05, with the labels that each got.

#40 Add an start_assisted_install step
  hardware_manager/ironic_coreos_install.py
  packages-list.ocp
  packages-list.okd
Labels: lgtm, approved

#45 Update the retry to Configuring UEFI
  hardware_manager/ironic_coreos_install.py
Labels: lgtm, approved

#44 Bug 2080446: Sync with latest ironic python agent
  packages-list.ocp
Labels: bugzilla/valid-bug, bugzilla/severity-high, lgtm, approved

#47 Bug 2086759: Bump retries for UEFI boot configuration
  hardware_manager/ironic_coreos_install.py
Labels: bugzilla/valid-bug, lgtm, approved, bugzilla/severity-unspecified

#48 Bug 2053752: Bump retries for UEFI boot configuration
  hardware_manager/ironic_coreos_install.py
Labels: bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, lgtm, approved, backport-risk-assessed

#49 Bug 2053752: import time
  hardware_manager/ironic_coreos_install.py
Labels: bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, lgtm, approved, backport-risk-assessed
