Repository openshift/ironic-agent-image, pull requests merged in 2023-07, with the labels that each got.

#84 [main] Switch to udevadm command install instead of package [OKD]
  packages-list.okd
Labels: lgtm, approved

#83 [release-4.13] Switch to udevadm command install instead of package [OKD]
  packages-list.okd
Labels: approved, backport-risk-assessed

#76 OCPBUGS-9072: Pass hostname within the ignition to coreos-installer
  hardware_manager/ironic_coreos_install.py
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
