Repository openshift/ironic-agent-image, pull requests merged in 2023-12, with the labels that each got.

#100 OCPBUGS-16607: 502 Proxy Error
  packages-list.ocp
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#103 OCPBUGS-25685: Relax packages requirements
  packages-list.ocp
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#101 OCPBUGS-19950: pick up the heartbeat retry fix
  packages-list.ocp
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
