Repository openshift/ironic-agent-image, pull requests merged in 2024-01, with the labels that each got.

#99 OCPBUGS-25351: 502 proxy error
  packages-list.ocp
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#104 METAL-850: Update packages for OCP 4.16
  packages-list.ocp
Labels: lgtm, approved, jira/valid-reference

#105 OCPBUGS-27781: Update ironic-python-agent with latest bug fixes
  packages-list.ocp
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#107 OCPBUGS-28554: Update to latest ironic-python-agent for bugfixes
  packages-list.ocp
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#106 OCPBUGS-19008: Always add ignition to set hostname on /etc/hostname
  hardware_manager/ironic_coreos_install.py
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
