Repository openshift/ironic-agent-image, pull requests merged in 2024-10, with the labels that each got.

#153 [4.12] OCPBUGS-38513: set webob and bump werkzeug
  packages-list.ocp
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#164 OCPBUGS-39384: Include fixes for CVE-2024-44082
  packages-list.ocp
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#155 OCPBUGS-39013: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#156 OCPBUGS-39017: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#157 OCPBUGS-39018: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#158 OCPBUGS-39019: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#167 METAL-1155: Update to latest ironic projects hash for OCP 4.18
  hardware_manager/ironic_coreos_install.py
  packages-list.ocp
  prepare-image.sh
  requirements.cachito
Labels: lgtm, approved, jira/valid-reference

#168 METAL-1164: Add pip no-build-isolation to download command
  prepare-image.sh
Labels: lgtm, approved, jira/valid-reference

#169 OCPBUGS-43546: Add ignition version number
  hardware_manager/ironic_coreos_install.py
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#170 NO-ISSUE: Update ironic projects hashes
  requirements.cachito
Labels: lgtm, approved, jira/valid-reference
