Repository openshift/ironic-agent-image, pull requests merged in 2024-08, with the labels that each got.

#144 OCPBUGS-38406: Update root image
  .ci-operator.yaml
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#145 OCPBUGS-38481: Update root image
  .ci-operator.yaml
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#147 OCPBUGS-38521: set webob and bump werkzeug
  packages-list.ocp
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#154 OCPBUGS-36492: Bump ironic-lib to fix utf8 decoding issue
  requirements.cachito
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
