Repository openshift/ironic-agent-image, pull requests merged in 2025-05, with the labels that each got.

#185 [4.17] OCPBUGS-55680: Delay determining the hostname to put into ignition
  hardware_manager/ironic_coreos_install.py
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#184 OCPBUGS-55350: collect the entire journal from the host
  hardware_manager/ironic_coreos_install.py
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#186 METAL-1264: Update to latest upstream content
  packages-list.ocp
  requirements.cachito
Labels: lgtm, approved, jira/valid-reference
